name: Hola mundo Actions GH

on: 
    push:
        branches:
            - main

jobs: 
    hola_mundo:
            name: Imrpimir Hola mundo 
            runs-on: self-hosted
            steps:
                - name: Revisar el repo
                  uses: actions/checkout@v2

                - name: install pandas
                  run: pip install pandas
                - name: Ejecutar condigo de python
                  run: python app.py
