name: Hola Mundo Actions GH

on: 
     push:
        branches:
            - main

jobs:
        hola_mundo:
                name: Imprimir Hola Mundo
                runs-on: ubuntu-latest
                steps:
                    - name: Revisar el Repositorio
                    uses: actions/checkout@v2

                    - name: Ejecutar codigo de python
                    uses: python3 app.py
                    

