name: Hola mundo Actions GH

on: 
    push:
        branches:
            - main

jobs: 
    hola_mundo:
            name: Imrpimir Hola mundo 
            runs-on: ubuntu-latest
            steps:
            - name: Imprimir Hola Mundo
           # run: echo "Hola Mundo"
